//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SETEA_Sistema.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SETEA_Sistema.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap agregar_producto {
            get {
                object obj = ResourceManager.GetObject("agregar-producto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap avatar {
            get {
                object obj = ResourceManager.GetObject("avatar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap avatar_de_usuario {
            get {
                object obj = ResourceManager.GetObject("avatar-de-usuario", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bruto {
            get {
                object obj = ResourceManager.GetObject("bruto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap busqueda_de_lupa {
            get {
                object obj = ResourceManager.GetObject("busqueda-de-lupa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap busqueda_de_lupa1 {
            get {
                object obj = ResourceManager.GetObject("busqueda-de-lupa1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap etiquetas_de_productos {
            get {
                object obj = ResourceManager.GetObject("etiquetas-de-productos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap firma {
            get {
                object obj = ResourceManager.GetObject("firma", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap image {
            get {
                object obj = ResourceManager.GetObject("image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap inventarioIco {
            get {
                object obj = ResourceManager.GetObject("inventarioIco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap llamada_telefonica {
            get {
                object obj = ResourceManager.GetObject("llamada-telefonica", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LogoSeteaHD {
            get {
                object obj = ResourceManager.GetObject("LogoSeteaHD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap oferta_especial {
            get {
                object obj = ResourceManager.GetObject("oferta-especial", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;es&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///    &lt;title&gt;Factura S E T E A&lt;/title&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///    &lt;div
        ///      style=&quot;
        ///        padding: 20px;
        ///        font-family: Arial, sans-serif;
        ///        max-width: 800px;
        ///        border-radius: 10px;
        ///        margin: 20px auto;
        ///      &quot;
        ///    &gt;
        ///      &lt;!-- Encabezado --&gt;
        ///      &lt;div style=&quot;text-align: center; margin-bottom: 20px&quot;&gt;
        ///        &lt;div style=&quot;font-size: 20px; font-weight: bold [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string PlantillaFactura {
            get {
                return ResourceManager.GetString("PlantillaFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;es&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///    &lt;title&gt;Factura S E T E A&lt;/title&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///    &lt;div
        ///      style=&quot;
        ///        padding: 20px;
        ///        font-family: Arial, sans-serif;
        ///        max-width: 800px;
        ///        border-radius: 10px;
        ///        margin: 20px auto;
        ///      &quot;
        ///    &gt;
        ///      &lt;!-- Encabezado --&gt;
        ///      &lt;div style=&quot;text-align: center; margin-bottom: 20px&quot;&gt;
        ///        &lt;div style=&quot;font-size: 20px; font-weight: bold [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string PlantillaFactura1 {
            get {
                return ResourceManager.GetString("PlantillaFactura1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;es&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///    &lt;title&gt;Lista de Compras SETEA&lt;/title&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///    &lt;div
        ///      style=&quot;
        ///        background-color: #f8f3f3;
        ///        padding: 20px;
        ///        font-family: Arial, sans-serif;
        ///        max-width: 800px;
        ///        border-radius: 10px;
        ///        margin: 20px auto;
        ///      &quot;
        ///    &gt;
        ///      &lt;!-- Encabezado --&gt;
        ///      &lt;div style=&quot;text-align: center; margin-bottom: 20px&quot;&gt;
        ///        &lt;div  [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string PlantillaListaDeCompras {
            get {
                return ResourceManager.GetString("PlantillaListaDeCompras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;es&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///    &lt;title&gt;Lista de Compras SETEA&lt;/title&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///    &lt;div
        ///      style=&quot;
        ///        background-color: #f8f3f3;
        ///        padding: 20px;
        ///        font-family: Arial, sans-serif;
        ///        max-width: 800px;
        ///        border-radius: 10px;
        ///        margin: 20px auto;
        ///      &quot;
        ///    &gt;
        ///      &lt;!-- Encabezado --&gt;
        ///      &lt;div style=&quot;text-align: center; margin-bottom: 20px&quot;&gt;
        ///        &lt;div  [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string PlantillaListaDeCompras1 {
            get {
                return ResourceManager.GetString("PlantillaListaDeCompras1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;es&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///    &lt;title&gt;Factura S E T E A&lt;/title&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///    &lt;div
        ///      style=&quot;
        ///        background-color: #f8f3f3;
        ///        padding: 20px;
        ///        font-family: Arial, sans-serif;
        ///        max-width: min-content;
        ///        border-radius: 10px;
        ///        margin: 20px auto;
        ///      &quot;
        ///    &gt;
        ///      &lt;!-- Encabezado --&gt;
        ///      &lt;div style=&quot;text-align: center; ma [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string PlantillaNew {
            get {
                return ResourceManager.GetString("PlantillaNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;es&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///    &lt;title&gt;Factura S E T E A&lt;/title&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///    &lt;div
        ///      style=&quot;
        ///        padding: 20px;
        ///        font-family: Arial, sans-serif;
        ///        max-width: min-content;
        ///        border-radius: 10px;
        ///        margin: 20px auto;
        ///      &quot;
        ///    &gt;
        ///      &lt;!-- Encabezado --&gt;
        ///      &lt;div style=&quot;text-align: center; margin-bottom: 20px&quot;&gt;
        ///        &lt;div st [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string PlantillaReporteUsuarios {
            get {
                return ResourceManager.GetString("PlantillaReporteUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;es&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///    &lt;title&gt;Factura S E T E A&lt;/title&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///    &lt;div
        ///      style=&quot;
        ///        padding: 20px;
        ///        font-family: Arial, sans-serif;
        ///        max-width: min-content;
        ///        border-radius: 10px;
        ///        margin: 20px auto;
        ///      &quot;
        ///    &gt;
        ///      &lt;!-- Encabezado --&gt;
        ///      &lt;div style=&quot;text-align: center; margin-bottom: 20px&quot;&gt;
        ///        &lt;div st [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string PlantillaReporteUsuarios1 {
            get {
                return ResourceManager.GetString("PlantillaReporteUsuarios1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;es&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///    &lt;title&gt;Factura S E T E A&lt;/title&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///    &lt;div
        ///      style=&quot;
        ///        padding: 20px;
        ///        font-family: Arial, sans-serif;
        ///        max-width: 800px;
        ///        border-radius: 10px;
        ///        margin: 20px auto;
        ///      &quot;
        ///    &gt;
        ///      &lt;!-- Encabezado --&gt;
        ///      &lt;div style=&quot;text-align: center; margin-bottom: 20px&quot;&gt;
        ///        &lt;div style=&quot;font-size: 20px; font-weight: bold [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string PlantillaReporteventas {
            get {
                return ResourceManager.GetString("PlantillaReporteventas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;es&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///    &lt;title&gt;Factura S E T E A&lt;/title&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///    &lt;div
        ///      style=&quot;
        ///        padding: 20px;
        ///        font-family: Arial, sans-serif;
        ///        max-width: 800px;
        ///        border-radius: 10px;
        ///        margin: 20px auto;
        ///      &quot;
        ///    &gt;
        ///      &lt;!-- Encabezado --&gt;
        ///      &lt;div style=&quot;text-align: center; margin-bottom: 20px&quot;&gt;
        ///        &lt;div style=&quot;font-size: 20px; font-weight: bold [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string PlantillaReporteventas1 {
            get {
                return ResourceManager.GetString("PlantillaReporteventas1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;es&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///    &lt;title&gt;Inventario SETEA&lt;/title&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///    &lt;div
        ///      style=&quot;
        ///        padding: 20px;
        ///        font-family: Arial, sans-serif;
        ///        max-width: 800px;
        ///        border-radius: 10px;
        ///        margin: 20px auto;
        ///      &quot;
        ///    &gt;
        ///      &lt;!-- Encabezado --&gt;
        ///      &lt;div style=&quot;text-align: center; margin-bottom: 20px&quot;&gt;
        ///        &lt;div style=&quot;font-size: 20px; font-weight: bold; [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string PlantillaReportProductos {
            get {
                return ResourceManager.GetString("PlantillaReportProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;es&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///    &lt;title&gt;Inventario SETEA&lt;/title&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///    &lt;div
        ///      style=&quot;
        ///        padding: 20px;
        ///        font-family: Arial, sans-serif;
        ///        max-width: 800px;
        ///        border-radius: 10px;
        ///        margin: 20px auto;
        ///      &quot;
        ///    &gt;
        ///      &lt;!-- Encabezado --&gt;
        ///      &lt;div style=&quot;text-align: center; margin-bottom: 20px&quot;&gt;
        ///        &lt;div style=&quot;font-size: 20px; font-weight: bold; [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string PlantillaReportProductos1 {
            get {
                return ResourceManager.GetString("PlantillaReportProductos1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap producto_de_codigo_de_barras {
            get {
                object obj = ResourceManager.GetObject("producto-de-codigo-de-barras", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap producto_de_codigo_de_barras1 {
            get {
                object obj = ResourceManager.GetObject("producto-de-codigo-de-barras1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap todos {
            get {
                object obj = ResourceManager.GetObject("todos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
