//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SETEA_Sistema.Modelodb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citas
    {
        public int Id { get; set; }
        public int ClienteId { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Servicio { get; set; }
        public Nullable<bool> RecordatorioEnviado { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
