//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SETEA_Sistema.Modelodb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Codigo_De_Productos
    {
        public int ID { get; set; }
        public string CodigoDelProducto { get; set; }
        public Nullable<int> ID_Producto_Enlazado { get; set; }
        public Nullable<System.DateTime> Fecha_De_Agregacion { get; set; }
    
        public virtual producto producto { get; set; }
    }
}
