//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SETEA_Sistema.Modelodb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SeteaEntities1 : DbContext
    {
        public SeteaEntities1()
            : base("name=SeteaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categorias> Categorias { get; set; }
        public virtual DbSet<ClienteCaja> ClienteCaja { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<estado> estado { get; set; }
        public virtual DbSet<MetodosPago> MetodosPago { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<VentaEnCaja> VentaEnCaja { get; set; }
        public virtual DbSet<Codigo_De_Productos> Codigo_De_Productos { get; set; }
        public virtual DbSet<Cliente_RP> Cliente_RP { get; set; }
        public virtual DbSet<Dispositivo_Info_RP> Dispositivo_Info_RP { get; set; }
        public virtual DbSet<Dispositivos_RP> Dispositivos_RP { get; set; }
        public virtual DbSet<Estados_RP> Estados_RP { get; set; }
        public virtual DbSet<Marca_Del_Dispositivo_RP> Marca_Del_Dispositivo_RP { get; set; }
        public virtual DbSet<Reparaciones_RP> Reparaciones_RP { get; set; }
        public virtual DbSet<Tipo_Dispositivos_RP> Tipo_Dispositivos_RP { get; set; }
        public virtual DbSet<Auditoria> Auditoria { get; set; }
        public virtual DbSet<Backups> Backups { get; set; }
        public virtual DbSet<Citas> Citas { get; set; }
        public virtual DbSet<DetallesVenta> DetallesVenta { get; set; }
        public virtual DbSet<facturaCaja> facturaCaja { get; set; }
        public virtual DbSet<Inventario> Inventario { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<Promociones> Promociones { get; set; }
        public virtual DbSet<PromocionesProductos> PromocionesProductos { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Ventas> Ventas { get; set; }
    }
}
