//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SETEA_Sistema.Modelodb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispositivo_Info_RP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dispositivo_Info_RP()
        {
            this.Dispositivos_RP = new HashSet<Dispositivos_RP>();
        }
    
        public int ID_Info_Dispositivo { get; set; }
        public Nullable<int> Tipo_Del_Dispositivo { get; set; }
        public Nullable<int> Marca_Del_Dispositivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dispositivos_RP> Dispositivos_RP { get; set; }
        public virtual Marca_Del_Dispositivo_RP Marca_Del_Dispositivo_RP { get; set; }
        public virtual Tipo_Dispositivos_RP Tipo_Dispositivos_RP { get; set; }

                public override string ToString() {
                        return this.ID_Info_Dispositivo.ToString();
                }
    }
}
