//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SETEA_Sistema.Modelodb
{
    using System;
    using System.Collections.Generic;
    
    public partial class facturaCaja
    {
        public int idFacturaCaja { get; set; }
        public Nullable<int> id_ClienteCaja { get; set; }
        public Nullable<System.DateTime> fecha_Compra { get; set; }
        public Nullable<decimal> totalCompra { get; set; }
    
        public virtual ClienteCaja ClienteCaja { get; set; }
    }
}
