//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SETEA_Sistema.Modelodb
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public producto()
        {
            this.VentaEnCaja = new HashSet<VentaEnCaja>();
            this.Codigo_De_Productos = new HashSet<Codigo_De_Productos>();
        }
    
        public int idProducto { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> PrecioUnidad { get; set; }
        public Nullable<int> cantidadRestante { get; set; }
        public Nullable<int> categoriaId { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string Estado { get; set; }
    
        public virtual Categorias Categorias { get; set; }
        public virtual estado estado1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VentaEnCaja> VentaEnCaja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Codigo_De_Productos> Codigo_De_Productos { get; set; }
    }
}
