//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SETEA_Sistema.Modelodb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reparaciones_RP
    {
        public int ID_Reparacion_RP { get; set; }
        public Nullable<int> Cliente { get; set; }
        public Nullable<int> Dispositivo_RP { get; set; }
        public Nullable<int> Estado_RP { get; set; }
        public Nullable<System.DateTime> Fecha_De_Ingreso { get; set; }
        public Nullable<System.DateTime> Fecha_De_Alta { get; set; }
        public Nullable<decimal> Cobro_Reparacion { get; set; }
        public string Diagnostico_Inicial { get; set; }
        public string Notas_Adicionales { get; set; }
    
        public virtual Cliente_RP Cliente_RP { get; set; }
        public virtual Dispositivos_RP Dispositivos_RP { get; set; }
        public virtual Estados_RP Estados_RP { get; set; }
    }
}
