//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SETEA_Sistema.Modelodb
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentaEnCaja
    {
        public int id { get; set; }
        public string ProductoNombre { get; set; }
        public string NumeroDelCliente { get; set; }
        public Nullable<int> idProdicto { get; set; }
        public Nullable<System.DateTime> FechaVenta { get; set; }
        public Nullable<int> cantidadProducto { get; set; }
        public Nullable<decimal> PrecioUnidad { get; set; }
        public Nullable<decimal> precioPorCantidad { get; set; }
        public string Nombre_cliente { get; set; }
        public string codigoDelProducto { get; set; }
        public Nullable<int> Descuento { get; set; }
    
        public virtual producto producto { get; set; }
    }
}
